FROM alpine 

RUN apk add build-base g++ cairo-dev jpeg-dev pango-dev giflib-dev nodejs npm


WORKDIR /server-app
COPY . .
RUN npm config set ignore-scripts false
RUN npm install

CMD ["npm", "run", "dev"]

